import Home from "./home/Home";
import Login from "./login/Login";
import Signup from "./signup/Signup";
import Checkout from "./checkout/Checkout";
import Product from "./product/Product";
import Payment from "./payment/Payment";
import Profile from "./profile/Profile";
import Notfound from "./notfound/Notfound";
import Address from "./address/Address";
import OrderSuccess from "./orderSuccess/OrderSuccess";
export { Home, Login, Signup, Checkout, Product, Payment, Profile ,Notfound,Address,OrderSuccess};
